### ISSUE TITLE
compare schemas tool comments/suggestions

### ISSUE THREAD

**Issue by tpatpa** [hed-standard/hed-server#139]
I have used the compare schemas tool from [https://hedtools.org/hed_dev/schemas](https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fhedtools.org%2Fhed_dev%2Fschemas&data=05%7C01%7Cattia.tal%40mayo.edu%7C3ceb36ff14604b50e70608db9d039b53%7Ca25fff9c3f634fb29a8ad9bdd0321f9a%7C0%7C0%7C638276411033295397%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=Ku1RGA4z%2FCi%2FtluaJ%2FuzMI8eobbxc6aLkz0f5SE2Gv4%3D&reserved=0) with:

- …/hed-schema-library/library_schemas/score/hedwiki/HED_score_1.1.0.mediawiki
- …/hed-schema-library/library_schemas/score/prerelease/HED_score_1.1.1.mediawiki
 
And also with:

- …/hed-schema-library/library_schemas/score/hedwiki/HED_score_1.0.0.mediawiki
- …/hed-schema-library/library_schemas/score/prerelease/HED_score_1.1.1.mediawiki
 
See attached ‘_differences.txt’ files.
 
Comments/suggestions:

- Add the path to ‘Schema1’ and ‘Schema2’ referred to in the text.
- Move the ‘Overall summary’ section to the end.
- Use short-form tags for ‘suggestedTag’ changes
- Can similar changes be grouped in a table? Something like this, for example:
 

```
Tag differences:

  requireChild:
  
   
  
      Tag                  Schema1              Schema2
      
      'Modulator'  True       None
      
      'Background-activity'               True       None
      
      'Background-activity-special-feature'                 True       None
      
      ….
      
      ….
      
      ….
  
   
  
  suggestedTag:
      
      Tag                  Schema1              Schema2
      
      'Continuous-background-activity'       Delta-activity-morphology,Theta-activity-morphology,Alpha-activity-morphology,Beta-activity-morphology,Gamma-activity-morphology,Brain-laterality,Brain-region,Sensors,Finding-extent              Rhythmic-activity-morphology,Brain-laterality,Brain-region,Sensors,Finding-extent
      
      'Nearly-continuous-background-activity'          Delta-activity-morphology,Theta-activity-morphology,Alpha-activity-morphology,Beta-activity-morphology,Gamma-activity-morphology,Brain-laterality,Brain-region,Sensors,Finding-extent              Rhythmic-activity-morphology,Brain-laterality,Brain-region,Sensors,Finding-extent
      
      ….
      
      ….
      
      ….
```

 
Tal

**Comment by VisLab** [comment]
The compare schemas tools has been modified.
